module.exports = {
    frontend: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts', dest: "frontend/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts', dest: "frontend/assets/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/themify-icons/fonts', dest: "frontend/assets/css/fonts"},
            {expand: true, src: "**", cwd: 'HTML/assets/images',     dest: "frontend/assets/images"},
            {expand: true, src: "**", cwd: 'HTML/assets/js',      dest: "frontend/assets/js"},
            {expand: true, src: "**", cwd: 'HTML/assets/videos',     dest: "frontend/assets/videos"},
            {src: 'HTML/master/_index.min.html', dest : 'frontend/index.html'},
            {src: 'HTML/master/_pages_about_company.min.html', dest : 'frontend/pages_about_company.html'},
            {src: 'HTML/master/_pages_about.min.html', dest : 'frontend/pages_about.html'},
            {src: 'HTML/master/_pages_team.min.html', dest : 'frontend/pages_team.html'},
            {src: 'HTML/master/_pages_services.min.html', dest : 'frontend/pages_services.html'},
            {src: 'HTML/master/_pages_careers.min.html', dest : 'frontend/pages_careers.html'},
            {src: 'HTML/master/_pages_faq.min.html', dest : 'frontend/pages_faq.html'},
            {src: 'HTML/master/_pages_contact.min.html', dest : 'frontend/pages_contact.html'},
            {src: 'HTML/master/_features_icons.min.html', dest : 'frontend/features_icons.html'},
            {src: 'HTML/master/_features_linear_icons.min.html', dest : 'frontend/features_linear_icons.html'},
            {src: 'HTML/master/_features_buttons.min.html', dest : 'frontend/features_buttons.html'},
            {src: 'HTML/master/_features_animations.min.html', dest : 'frontend/features_animations.html'},
            {src: 'HTML/master/_features_typograpy.min.html', dest : 'frontend/features_typograpy.html'},
            {src: 'HTML/master/_features_grid_system.min.html', dest : 'frontend/features_grid_system.html'},
            {src: 'HTML/master/_features_header_2.min.html', dest : 'frontend/features_header_2.html'},
            {src: 'HTML/master/_features_header_3.min.html', dest : 'frontend/features_header_3.html'},
            {src: 'HTML/master/_features_footer_2.min.html', dest : 'frontend/features_footer_2.html'},
            {src: 'HTML/master/_features_footer_3.min.html', dest : 'frontend/features_footer_3.html'},
            {src: 'HTML/master/_features_page_title_simple.min.html', dest : 'frontend/features_page_title_simple.html'},
            {src: 'HTML/master/_features_page_title_image.min.html', dest : 'frontend/features_page_title_image.html'},
            {src: 'HTML/master/_extra_search_result.min.html', dest : 'frontend/extra_search_result.html'},
            {src: 'HTML/master/_extra_pricing_table.min.html', dest : 'frontend/extra_pricing_table.html'},
            {src: 'HTML/master/_extra_starter_page.min.html', dest : 'frontend/extra_starter_page.html'},
            {src: 'HTML/master/_extra_maintenance.min.html', dest : 'frontend/extra_maintenance.html'},
            {src: 'HTML/master/_extra_404.min.html', dest : 'frontend/extra_404.html'},
            {src: 'HTML/master/_extra_500.min.html', dest : 'frontend/extra_500.html'},
            {src: 'HTML/master/_slider_horizontal.min.html', dest : 'frontend/slider_horizontal.html'},
            {src: 'HTML/master/_slider_vertical.min.html', dest : 'frontend/slider_vertical.html'},
            {src: 'HTML/master/_slider_nested.min.html', dest : 'frontend/slider_nested.html'},
            {src: 'HTML/master/_slider_effects.min.html', dest : 'frontend/slider_effects.html'},
            {src: 'HTML/master/_slider_thumbs.min.html', dest : 'frontend/slider_thumbs.html'},
            {src: 'HTML/master/_slider_carousel.min.html', dest : 'frontend/slider_carousel.html'},
            {src: 'HTML/master/_portfolio_example1.min.html', dest : 'frontend/portfolio_example1.html'},
            {src: 'HTML/master/_portfolio_example2.min.html', dest : 'frontend/portfolio_example2.html'},
            {src: 'HTML/master/_portfolio_example3.min.html', dest : 'frontend/portfolio_example3.html'},
            {src: 'HTML/master/_portfolio_item.min.html', dest : 'frontend/portfolio_item.html'},
            {src: 'HTML/master/_blog_page.min.html', dest : 'frontend/blog_page.html'},
            {src: 'HTML/master/_blog_page_left_sidebar.min.html', dest : 'frontend/blog_page_left_sidebar.html'},
            {src: 'HTML/master/_blog_page_small_images.min.html', dest : 'frontend/blog_page_small_images.html'},
            {src: 'HTML/master/_blog_post.min.html', dest : 'frontend/blog_post.html'}
        ]
    }
};
